/*
 Adruino_SpaceNode.h - Library for ESP8266 Arduino Sensor Nodes

 Created by: Steve Lammers, 10/28/2017

 Adapted from the supplied MQTT example by Keith M. Hughes.


  ToDo------------------------
  MDNS
  MQTT
  structure that contains topic names (default names)

  End user provides a 
    - SSID, 
    - sensing node: a topic for data on 
                    supply a method that reads the sensors
                      we provide a method to put the json message toghther
*/

#ifndef ARDUINO_SPACENODE
#define ARDUINO_SPACENODE

#ifndef ARDUINO
#endif //ARDUINO


// Update these with values suitable for your network.

// The SSID of the wireless network to attach to.
//oconst char* ssid = "TinkerMill";
#define SSID "TinkerMill"

// The password for the wireless network.
const char* password = "";

// The following describe the MQTT topics and client ID.

// The ID the MQTT client should have.
//
// This should have something unique, like your name.
//
// However, we will autogenerate it using the ESP Chip ID.
char mqttClientId[64];

// The topic to subscribe to.
const char* mqttControlInputTopic = "/tinkermill/sensors/control";

// The WiFi client used to connect to the wireless network.
WiFiClient wifiClient;

// The MQTT Pub/Sub client
PubSubClient mqttCient(wifiClient);

// The host name for the chip on mDNS.
//
// This will be autogenerated.
char hostName[24];

// The writable pins on the Sparkfun Thing Dev board.
const int WRITABLE_PINS[] = { 0, 2, 4, 5, 12, 13, 14, 15, 16 };

// The number of writable pins
const int NUM_WRITABLE_PINS = sizeof(WRITABLE_PINS) / sizeof(int);


#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <PubSubClient.h>


#endif //ARDUINO_SPACENODE
