/*
 Adruino_SpaceNode.h - Library for ESP8266 Arduino Sensor Nodes

 Created by: Steve Lammers, 10/28/2017

 Adapted from the supplied MQTT example by Keith M. Hughes.


  ToDo------------------------
  MDNS
  MQTT
  structure that contains topic names (default names)

  End user provides a 
    - SSID, 
    - sensing node: a topic for data on 
                    supply a method that reads the sensors
                      we provide a method to put the json message toghther
*/

#ifndef ARDUINO_SPACENODE
#define ARDUINO_SPACENODE

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <PubSubClient.h>



class SpaceNode{

  const char* ssid, password, mqttControlInputTopic;

  // The following describe the MQTT topics and client ID.
  // The ID the MQTT client should have.
  // This should have something unique, like your name.
  // However, we will autogenerate it using the ESP Chip ID.
  char mqttClientId[64];

  // The host name for the chip on mDNS.
  // This will be autogenerated.
  char hostName[24];

  // The WiFi client used to connect to the wireless network.
  WiFiClient wifiClient;

  // The MQTT Pub/Sub client
  PubSubClient mqttCient(wifiClient);

  public:
  // Constructor
  SpaceNode();
  // Deconstructor
  ~SpaceNode();

  void setup();
  void setup_wifi();
  void setup_mqtt_session()
  void mqttCallback(char* topic, byte* payload, unsigned int length);
  void reconnect();

};



#endif //ARDUINO_SPACENODE
